### ISSUE TITLE
skorch builds failing

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-dev-recipes#141]
@cxhernandez: It looks like skorch builds are failing on `osx`:
```
===== testing package: skorch-0.3.0a0-py35_0 =====

running run_test.py

/opt/conda/conda-bld/skorch_1533290184797/_t_env/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88

  return f(*args, **kwds)

/opt/conda/conda-bld/skorch_1533290184797/_t_env/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88

  return f(*args, **kwds)

Traceback (most recent call last):

  File "/opt/conda/conda-bld/skorch_1533290184797/test_tmp/run_test.py", line 5, in <module>

    import skorch

  File "/opt/conda/conda-bld/skorch_1533290184797/_t_env/lib/python3.5/site-packages/skorch/__init__.py", line 28, in <module>

    raise ImportWarning(msg.format(req=MIN_TORCH_VERSION, installed=torch_version))

ImportWarning: skorch depends on a newer version of PyTorch (at least 0.4.1, not 0.4.0). Visit https://pytorch.org for installation details

TESTS FAILED: skorch-0.3.0a0-py35_0.tar.bz2

ERROR: File does not exist: /opt/conda/conda-bld/linux-64/skorch-0.3.0a0-py35_0.tar.bz2
```
Can you confirm that you still want dev packages of `skorch` built? If not, can you fix the skorch upstream tests, or recipe tests?

**Comment by cxhernandez** [comment]
It should be [skipping `osx` builds](https://github.com/omnia-md/conda-dev-recipes/blob/master/skorch/meta.yaml#L15). Did I set up the `meta.yaml` wrong?

**Comment by jchodera** [comment]
Whoops! You're right---the failures are actually on `linux` instead: 
See the linux failures here:
https://travis-ci.org/omnia-md/conda-dev-recipes

You have to click the raw logs:
https://api.travis-ci.org/v3/job/412046190/log.txt

**Comment by jchodera** [comment]
@cxhernandez : It looks like the build is failing because of [a pytorch dependency](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/412278089#L7682-L7694):
```
===== testing package: skorch-0.3.0a0-py35_0 =====
running run_test.py
/opt/conda/conda-bld/skorch_1533462689728/_t_env/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/opt/conda/conda-bld/skorch_1533462689728/_t_env/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Traceback (most recent call last):
  File "/opt/conda/conda-bld/skorch_1533462689728/test_tmp/run_test.py", line 5, in <module>
    import skorch
  File "/opt/conda/conda-bld/skorch_1533462689728/_t_env/lib/python3.5/site-packages/skorch/__init__.py", line 28, in <module>
    raise ImportWarning(msg.format(req=MIN_TORCH_VERSION, installed=torch_version))
ImportWarning: skorch depends on a newer version of PyTorch (at least 0.4.1, not 0.4.0). Visit https://pytorch.org for installation details
TESTS FAILED: skorch-0.3.0a0-py35_0.tar.bz2
```
In addition, 0.3.0 [was released 10 days ago](https://github.com/dnouri/skorch/releases) but your `dev` build is still claiming to build 0.3.0a.

If it's not possible for you to maintain this package and you don't need the bleeding-edge latest builds, can we just get rid of it and keep the production releases in omnia? We can update that package with the very recent 0.3.0 release.
