### ISSUE TITLE
conda-build-all broken?

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-dev-recipes#41]
https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/161802990#L357-L372

```
'/io/README.md', '/io/appveyor.yml', '/io/conda-build-all', '/io/devtools', '/io/openmm', '/io/parmed']
Skipping '/io/devtools' because no meta.yaml file found...
Considering recipes in the following order:
openmm, parmed
updating index in: /anaconda/conda-bld/linux-64
Fetching package metadata ...........
Traceback (most recent call last):
  File "/io/conda-build-all", line 447, in <module>
    sys.exit(main())
  File "/io/conda-build-all", line 119, in main
    return execute(args, p)
  File "/io/conda-build-all", line 417, in execute
    to_build = list(required_builds(metadatas, pythons, numpys, channel_urls, verbose=args.verbose, force=args.force))
  File "/io/conda-build-all", line 319, in required_builds
    bldpkg_path = get_bldpkg_path(m, python, numpy)
  File "/io/conda-build-all", line 228, in get_bldpkg_path
    return conda_build_build.bldpkg_path(m, cfg)
TypeError: bldpkg_path() takes 1 positional argument but 2 were given
+ true
```

**Comment by jchodera** [comment]
@marscher : Any ideas?

**Comment by marscher** [comment]
is conda-build-all downloaded from conda-recipes or an extra copy in this repo? I have to admin that I got confused... 

If it comes from the central repo, we also need to pin conda-build to 2.0.1 of course :+1:

**Comment by jchodera** [comment]
It's downloaded from `conda-recipes`.

**Comment by jchodera** [comment]
> If it comes from the central repo, we also need to pin conda-build to 2.0.1 of course 👍

Will do!
