### ISSUE TITLE
pdflatex figure

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-dev-recipes#84]
Any idea why [this is failing](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/219656246#L4750-L4777) @Lnaden @peastman ?
```
gmake[4]: *** [latexpdf] Error 1
make[3]: *** [sphinx-docs/userguide/latex/OpenMMUsersGuide.pdf] Error 2
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [docs-source/CMakeFiles/sphinxpdf.dir/all] Error 2
make[1]: *** [docs-source/CMakeFiles/sphinxpdf.dir/rule] Error 2
make: *** [sphinxpdf] Error 2
Traceback (most recent call last):
  File "/anaconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/anaconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 334, in main
    execute(sys.argv[1:])
  File "/anaconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 325, in execute
    noverify=args.no_verify)
  File "/anaconda/lib/python3.6/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/anaconda/lib/python3.6/site-packages/conda_build/build.py", line 1503, in build_tree
    config=config)
  File "/anaconda/lib/python3.6/site-packages/conda_build/build.py", line 1135, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/anaconda/lib/python3.6/site-packages/conda_build/utils.py", line 620, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/conda_build/utils.py", line 616, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/anaconda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/anaconda/conda-bld/openmm_1491567224506/work/conda_build.sh']' returned non-zero exit status 2.
```

**Comment by Lnaden** [comment]
It looks like there might have been something that changed in the docs in Chapter 7. The actual error [happened a few lines before your post](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/219656246#L4726-L4733) and propagated up from `pybtex`.

based on the travis logs, the error started 2 days ago, which happened after pandegroup/openmm#1009 occurred. The offending entry is [here](https://github.com/pandegroup/openmm/blob/master/docs-source/usersguide/references.bib#L529) where a comma is missing in the bibTex entry. I'll open a PR to fix it.

**Comment by jchodera** [comment]
Thanks!
